---
# Common task

- name: default package upgrade
  apt: upgrade=yes update_cache=yes cache_valid_time=86400

- name: install ntpd
  apt: name=ntp

- name: Install hosts
  template: src=hosts.j2 dest=/etc/hosts
